# Generated by Django 4.2.2 on 2023-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('abbr_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=255)),
                ('club_name', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=100)),
                ('num_people', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
    ]
